services:
  ofelia:
    image: ghcr.io/netresearch/ofelia
    container_name: ofelia
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conf/:/etc/ofelia/
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.routers.ofelia.rule: Host(`ofelia.69b.place`)
      traefik.http.services.ofelia.loadbalancer.server.port: 8080

      homepage.group: System
      homepage.name: Ofelia
      homepage.description: Scheduled Jobs
      homepage.icon: https://camo.githubusercontent.com/7f2c551d2a3c6af164a47b2d87599cd085404668b3249fecb774b33dbfd4504b/68747470733a2f2f776569726473706163652e646b2f4672616e636973636f4962616e657a2f47726170686963732f4f66656c69612e676966
      homepage.href: https://ofelia.69b.place

networks:
  traefik:
    name: traefik
    external: true
